language: node_js
node_js:
  - 10.15
install:
  - npm uninstall -g angular/cli
  - npm uninstall --save-dev angular-cli
  - rm -rf node_modules dist
  - npm cache clean --force
  - npm install -g @angular/cli@latest
  - npm install --save-dev @angular/cli@latest
  - npm install
script:
  - ng update @angular/cli --migrate-only --from=1.7.4
  - ng build
  - cd dist
  - ls -al
